### ISSUE TITLE
How to start pyspark?

### ISSUE THREAD

**Issue by quanghoc** [tetra-concepts-llc/spark-training-vm#3]
The `docker run -it --rm kevinfaro/tetra_spark` command line goes directly to scala. How do I start pyspark? 

Also how to copy file from local Mac filesystem into the VM HDFS?

**Comment by kevin-faro** [comment]
Sorry, this repo was intended only for the spark meetup we ran in early December.

If you want to launch right into a bash shell, you can add "bas" at the end of the docker run command.  

As for getting data into your docker image, here is some documentation: https://docs.docker.com/engine/reference/commandline/cp/
